name: CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: horochx/deploy-via-scp@1.0.1
      with:
        local: "src" # eg: dist
        host: ${{ secrets.HOST }} # eg: example.com
        port: ${{ secrets.PORT }} # eg: 22
        user: ${{ secrets.USER }} # eg: github-action
        key: ${{ secrets.KEY }} 
        remote: "~/docker/website"
